
platform :ios, '9.0'
inhibit_all_warnings!
target '573music' do
pod 'YTKNetwork', '~> 2.0.4'
pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'WMPageController', '~> 2.3.0'
pod 'Qiniu'
pod 'LYEmptyView'
pod 'JJException'
pod 'YBImageBrowser'
#pod 'Hyphenate', '~> 3.6.5'
pod 'JPush', '3.2.2-noidfa'
pod 'LookinServer', :configurations => ['Debug']
pod 'Masonry'
pod 'FSTextView'
pod 'SVGAPlayer'
#pod 'AMap3DMap'
#pod 'AMapSearch'
pod 'LEEAlert'
pod 'UMCCommon'
pod 'PPBadgeView'
#pod 'WechatOpenSDK'
pod 'CHTCollectionViewWaterfallLayout'
pod 'YYText'
end
